### ISSUE TITLE
Persistent notification not disappearing even after leaving the app with the back button

### ISSUE THREAD

**Issue by VincentJoshuaET** [zacharee/SamloaderKotlin#26]
I have to remove the app from recents. I don't think this is good behavior.

Why is a notification needed in the first place? I didnt even try to download anything

**Comment by zacharee** [comment]
Because this is a cross-platform project, and the tooling isn't there for everything, this is a compromise that needs to be made for now. The notification is there because a foreground Service is used to manage the downloads on Android (to allow background downloading). Foreground Services require notifications.

In the future, I might revisit how and when the Service is started, but it's just going to be this way for now. You can always disable the notification.
